### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by davidbuckhurst** [bbc/bbc.github.io#5]
I'm sure this was working, but now it's saying:

Your site is having problems building: Validation failed: User must be a human, not an Organization

Not seen that before

**Comment by dhinus** [comment]
Yeah it worked initially then it broke... annoying.

According to [this comment](https://github.com/forfutureLLC/bara/issues/1#issuecomment-68589122) it could be because there was already a "project page" deployed on the same domain. In our case it could be [this one](https://github.com/bbc/internalgel/tree/gh-pages).

**Comment by dhinus** [comment]
I'll try deleting the `gh-pages` branch from that other repo and see if it makes a difference.

**Comment by davidbuckhurst** [comment]
Hmm, can you not have both organisation and project level sites? We have a number of gh-pages sites too -- I imagine a lot of teams use them.

**Comment by dhinus** [comment]
Yeah I wonder if every time someone pushes one of the `gh-pages` sites everything will break again...

For now it's fixed. What I did:
- deleted the `gh-pages` branch on https://github.com/bbc/internalgel
- pushed a commit to `master` on https://github.com/bbc/bbc.github.io
- recreated the `gh-pages` branch on https://github.com/bbc/internalgel

**Comment by dhinus** [comment]
Closing the issue, will reopen if this happens again...
